### ISSUE TITLE
Angular中文版本文档翻译纠错 

### ISSUE THREAD

**Issue by islanders-zz** [ng-docs/angular-cn#10]
### Description

在Angular中文版文档的**开发指南**中的**路由与导航章节**中的**教程:为英雄之旅添加路由支持**中**在列表视图中设置路由参数**这一小节中的"路由器从该数组中组合出了目标 URL：localhost:**3000**/hero/15。"端口号3000应改正为4200

### What is the affected URL?

https://angular.cn/guide/router-tutorial-toh

**Comment by asnowwolf** [comment]
多谢！已改正！当初做同步更新的时候没仔细检查，请多多留意，随时纠正。
