### ISSUE TITLE
Error 522 Connection timed out

### ISSUE THREAD

**Issue by LuigiImVector** [ng-docs/angular-cn#12]
### Description

It's impossible to access the Chinese site of angular

### What is the affected URL?

https://angular.cn/

### Please provide the steps to reproduce the issue

Go to the website

**Comment by wszgrcy** [comment]
Maybe network fluctuations ? I can access it in beijing.(no cache)

**Comment by LuigiImVector** [comment]
Trying a VPN from Japan, the United States and the Netherlands (the only countries available on ProtonVPN free) tells me directly "We can't connect to the server at angular.cn."

Without VPN "error 522," I live in italy.

**Comment by davorpa** [comment]
> Without VPN "error 522," I live in italy.

Me too from Spain. A "522 screen error" on Cloudflare CDN is raised

![image](https://user-images.githubusercontent.com/3125580/183159921-9a567b7e-648e-411d-a975-ea00696d6b6f.png)

Routing from Honk Kong via VPN is the same

**Comment by Kai-Qiao** [comment]
https://github.com/ng-docs/ng-docs.github.io/issues/184
i tried routing from Beijing, Shanghai, Tokyo, Singapore it's the same result
![image](https://user-images.githubusercontent.com/18208709/183563352-ae6875a4-9a49-47f1-8d85-b786cb92de02.png)

**Comment by asnowwolf** [comment]
Thanks for pointing this out, I'll look into this.

Until then, please visit angular.live, which is hosted on Github Pages and is the CDN origin for angular.cn.

**Comment by asnowwolf** [comment]
Solved. Could you please help me verify it?

**Comment by LuigiImVector** [comment]
now it works, thank you

**Comment by davorpa** [comment]
It works for me too.

**Comment by Kai-Qiao** [comment]
thanks, it runs well now.
