### ISSUE TITLE
缺少 NgOptimizedImage 翻译

### ISSUE THREAD

**Issue by huajian123** [ng-docs/angular-cn#14]
### 出错的文档地址

https://angular.cn/

### 英文文本和目前的文本

https://angular.io/api/common/NgOptimizedImage

**Comment by wszgrcy** [comment]
竟然多了一个这种api...不过为啥感觉应该放cdk里合适呢?

**Comment by asnowwolf** [comment]
已经翻译了，卡在发布上。
