### ISSUE TITLE
关于翻译的实现方式疑问

### ISSUE THREAD

**Issue by EnochGao** [ng-docs/angular-cn#17]
### 出错的文档地址

https://angular.cn/guide/image-directive

### 英文文本和目前的文本

https://angular.cn/guide/image-directive

### 您认为这种译法有什么问题？

催更👀👀👀

关于翻译我有一些疑问：
- 仓库是fork的吗？
- 翻译的原理是什么，我观察到对应的源码注释也被翻译了，那么如果源ng仓库对应注释或者代码进行了调整，合并到此仓库会不会被覆盖掉（产生冲突）？怎么感知源仓库的修改？

**Comment by asnowwolf** [comment]
1. 仓库是 fork 的。
2. 主要是借助 git 的合并功能进行自动合并，不过也有不少手工的工作量，有些冲突要手动解决。现在 ng 的特性和文档都很稳定了，所以工作量并不大，如果没有遇到技术问题，基本上一个月内能同步完。

**Comment by asnowwolf** [comment]
以前都能在一个月内翻译完毕。不过这次翻译延迟主要就是构建系统换成 bazel 了，有一些奇怪的问题不知道怎么解决，所以没法发布。翻译都已经完成了。

**Comment by EnochGao** [comment]
> 

狼叔辛苦，感谢👍👍👍
