### ISSUE TITLE
Angular中文版本文档翻译纠错

### ISSUE THREAD

**Issue by islanders-zz** [ng-docs/angular-cn#9]
### Description

在Angular中文版文档的英雄之旅教程第六部分, **从服务器中获取数据**这一章节中的**创建HeroSearchComponent**部分的最后一段文字'**当用户在搜索框中输入时，一个 keyup 事件绑定会调用该组件的 search() 方法，并传入新的搜索框的值'** 中的**keyup事件**翻译有误, 应改为**input事件**

### What is the affected URL?

https://angular.cn/tutorial/toh-pt6

**Comment by asnowwolf** [comment]
已改正
